### ISSUE TITLE
Add Notice to Top Soil Matches module  - Enter data for better results

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1270] opened 2024-05-09 14:50 UTC
Add text to Soil ID page

`Notice
These matches are based on soil maps only. To improve the results, collect some data at this site (see Site Data below.)`

### Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=4740-11924&t=OaugOi7bsxa5A84r-0)

#### Design as of 5/9/2024, see Figma for most up-to-date version
<img width="342" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/164a7a22-c1c7-4c72-941c-1f7c4772773d">

## Acceptance Criteria
- [ ] Add text box with notice beneath the Top Soil Matches header

**Comment by paulschreiber** [comment] 2024-08-05 19:16
This is a duplicate of https://github.com/techmatters/terraso-mobile-client/issues/1226.

**Closed by paulschreiber** 2024-08-05 19:16 UTC
Labels: Engineering
