### ISSUE TITLE
Project manager unable to select unaffiliated site to transfer into project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#958] opened 2024-03-20 21:08 UTC
### App Version

102

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Carissa was unable to select a site she had created to transfer it into a project she had created

### Steps to Reproduce

1. Create a site
2. Create a project
3. Open the project and switch to the Sites tab
4. Click Transfer Sites
5. Attempt to select the site you just created

### Expected behavior

Site should be selectable

### Actual behavior

Site was not selectable

### Additional context

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/f1110101-94d5-426e-aade-6bdc766addd6)

**Comment by DerekCaelin** [comment] 2024-04-22 17:54
Closing because this experience wasn't actually implemented (so not a bug). The backend work to do site transfer to projects is here: https://github.com/techmatters/terraso-backend/issues/1250

**Closed by DerekCaelin** 2024-04-22 17:54 UTC
Labels: bug, slim MVP, permissions
