### ISSUE TITLE
Reduce max char limit for site and project titles to 50 characters

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#674] opened 2023-12-06 20:45 UTC
Set the max character length for Site and Project names to 50 characters.

## Acceptance Criteria
- [ ] Site
- [ ] Project

**Comment by CourtneyLee333** [comment] 2023-12-06 20:48
Yes!

**Comment by ltseng** [comment] 2023-12-06 21:22
Ok, editing the title and description then. Thanks!

**Comment by DerekCaelin** [comment] 2024-04-30 16:11
Still issue as of 118. Trimmed the description.

**Comment by DerekCaelin** [comment] 2024-04-30 16:14
Closing as duplicate of https://github.com/techmatters/terraso-mobile-client/issues/534

**Closed** 2024-05-17 13:59 UTC
Labels: slim MVP
