### ISSUE TITLE
Extract FormOverlaySheet from current InfoOverlaySheet and standardize usages

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1333] opened 2024-05-15 21:24 UTC
The updated design specification for overlay sheets distinguishes [sheets for forms](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7202-34072&t=KubZnYZzlmVx22S0-0) (`FormOverlaySheet`) from sheets displaying information (`InfoOverlaySheet`). Extract a new component for forms from the current implementation, simplify the `InfoOverlaySheet` implementation, and standardize any existing usages of the form style. Coordinate with designer for resolving any specific issues / inconsistencies.

**Comment by knipec** [comment] 2024-07-30 21:10
From Ruxandra: This is a duplicate of #1774

**Closed** 2024-07-30 21:10 UTC
Labels: tech-debt, Engineering
