### ISSUE TITLE
Build menu for rating soil match

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#761] opened 2024-01-09 21:36 UTC
This menu allows users to:
- say "this is not my soil"
- say "this is my soil"
- say "I'm not sure if this is my soil" (default)

It is accessible from the soil information sheet (#760) and if the user chooses either of the first two options above, there will be implications for the display of items on the soil information sheet.

Check for the [most recent design release](https://www.figma.com/files/project/87085153/LandPKS?fuid=1209917626938630763)

**Comment by DerekCaelin** [comment] 2024-05-23 14:13
Closing as duplicate of https://github.com/techmatters/terraso-mobile-client/issues/1162

**Closed by DerekCaelin** 2024-05-23 14:13 UTC
Labels: slim MVP
