### ISSUE TITLE
On project inputs screen, default to expand accordions and add space at the bottom

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#956] opened 2024-03-20 20:41 UTC
As currently implemented, the save button occludes the required inputs accordion on the Project Inputs tab.

Following the design, open the Depth an Required fields accordions and add space enough at the bottom for the save button to hover without occluding anything.

## Design
[Figma
](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12975&t=OektX8lIEcjdLAYG-0)

## Acceptance criteria
- [x]   open accordions
- [ ]     add space beneath accordions so that save button at lowest point doesn't occlude anything

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/5cf26b25-c636-492b-9687-97e3d1f5b509)

**Comment by ltseng** [comment] 2024-03-20 20:42
@CourtneyLee333 let me know if you think the right approach would be to default to having the accordions open. We will probably need to fix the non scrolling behavior either way if the user ends up closing one or the other.

**Comment by CourtneyLee333** [comment] 2024-03-20 21:16
I do think the right approach is to default to accordions open in general. But we also have a design pattern where a screen should always be scrollable far enough to show all the content above any FABs at the bottom. In other words, have an inch or so of blank space at the bottom of the content.

**Comment by knipec** [comment] 2024-07-16 22:41
Do you consider this part of the components library work? If so, can we close this? @tm-ruxandra @CourtneyLee333

**Comment by tm-ruxandra** [comment] 2024-07-17 14:20
@knipec This seems like more of a bug; the issue is less the design than the implementation detail of how far the user can scroll.

**Comment by DerekCaelin** [comment] 2024-07-17 14:33
Seems like the solution @CourtneyLee333 has expressed is:
- open accordions 
- add space beneath accordions so that save button at lowest point doesn't occlude anything

Will revise the issue

**Comment by knipec** [comment] 2024-07-19 02:18
@tm-ruxandra I was thinking the solution might be something like "all accordions should make sure the bottommost item has X amount of space at the bottom that would happen to accommodate the floating button" -- are you thinking that wouldn't be the solution, or that that solution wouldn't be components library work?

**Comment by tm-ruxandra** [comment] 2024-07-19 15:51
@knipec yeah, I think this is in a grey area where component designs alone aren't the sole issue here.

**Comment by paulschreiber** [comment] 2024-08-07 21:03
Please verify expanded state on 179. (The space beneath will be addressed with component work.)

**Comment by knipec** [comment] 2024-08-08 16:53
Looking at our [Component Library tasks](https://github.com/orgs/techmatters/projects/7/views/1?filterQuery=+-status%3ADone+-label%3A%22user+story%22+label%3A%22Component+Library%22) and Ruxandra's comment above, I believe the space beneath to accommodate the FAB is actually not planned to be addressed with component work. I expect that should be pretty easy to add though -- @paulschreiber is that something you can do?

**Comment by paulschreiber** [comment] 2024-08-09 14:50
@knipec I'm not sure what this would look like. This particular screen doesn't have. problem with the button occluding content.

**Comment by paulschreiber** [comment] 2024-08-13 16:25
@DerekCaelin that's a different screen design; it doesn't have multiple sections.

**Comment by knipec** [comment] 2024-08-13 16:35
Ohh I see, I was just thinking about it for the project inputs screen in particular, to prevent the issue depicted in the image in the Acceptance Criteria description above. I didn't realize that it was desired for every screen with a FAB, but that makes sense to me. Hmm in that case I can make a component library task for it, and just include figuring out the implementation details as part of the task? Lmk if that sounds good and I can do that? @paulschreiber @DerekCaelin @CourtneyLee333

**Comment by CourtneyLee333** [comment] 2024-08-13 16:59
I've already outlined the desired behavior in the component documentation, so it makes sense to me to include it in component implementation.

**Comment by knipec** [comment] 2024-08-13 22:29
Ah ok, apologies, I had been looking through the components stories for "FAB" -- but looks like it's intended to be addressed as part of https://github.com/techmatters/terraso-mobile-client/issues/1856 in which case I am satisfied :)

**Closed** 2024-08-14 00:21 UTC
Labels: bug, needs triage
