### ISSUE TITLE
ES Full Description link crashes app

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1715] opened 2024-07-05 14:51 UTC
Tapping the link for Ecological Site Full Description on a soil info sheet causes the app to crash on Android and iOS. 

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/2d615d8b-75c4-4775-bd4d-b73a0d8283ec)

**Comment by tm-ruxandra** [comment] 2024-07-05 20:35
This is caused by Soil ID not always returning a valid URL for ecological sites/soil series even when a site is present. We can disable the links if a URL is absent, but this may indicate a deeper issue with the algorithm / unexpected gaps in data.

**Comment by CourtneyLee333** [comment] 2024-07-08 18:47
@shrouxm We suspect the algorithm is no longer returning Ecological Site Description URLs. In the last build the link was crashing the app. In this build, after Ruxandra's work here, the link is not displaying at all. Will you look into this?

**Comment by shrouxm** [comment] 2024-07-11 23:58
i looked into this briefly, confirmed that the backend is just not returning an ESD url for any soils anymore. I'm not sure what might have caused this since I don't think we've updated the soil id algorithm code, unless one of our underlying API providers is returning different data now. I'll need to look into it more next week.

**Comment by paulschreiber** [comment] 2024-07-12 03:00
We're not crashing any more and can close this.

**Closed by paulschreiber** 2024-07-12 03:00 UTC
Labels: bug, crash

**Comment by CourtneyLee333** [comment] 2024-07-12 12:35
Noting we need another issue to describe the URLs no longer showing.
