### ISSUE TITLE
Soil ID - Top Soil Matches - Notice - No published soil map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1272] opened 2024-05-09 15:13 UTC
Inform the user when the Soil ID algorithm returns no response because there is no published soil map for a given location, and link them to external resources.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?t=nIiJTJshDPZ5i7Wb-0)
```
Soil map data not published
The soil map data for your location is not published. Please consult your state soil scientist at to request access to this data. Soil resources for Native lands:
```
#### Design as of 5/9/2024, please see figma for most up-to-date design
<img width="337" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/801b86cc-8d6f-4de4-a839-21669dd2e9ab">

## Acceptance Criteria
- [ ] Display the notice when the Soil ID algorithm provides no information because there is no published soil map for an area

**Comment by paulschreiber** [comment] 2024-08-05 19:18
Duplicate of https://github.com/techmatters/terraso-mobile-client/issues/1228

**Closed by paulschreiber** 2024-08-05 19:18 UTC
Labels: Engineering
