### ISSUE TITLE
Non-Managers are able to select editable fields on Project Settings screen, but not save changes

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#500] opened 2023-10-13 20:38 UTC
### App Version

46

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Viewers can tap into editable fields like a project name, privacy, description, and instructions/pinned notes, but the Save button silently fails.

### Steps to Reproduce

1. As a project viewer or contributor, open a project

### Expected behavior

Viewers and contributors should not be able to make changes to the project name, description, privacy, or instructions/pinned notes. The Save button should be hidden or disabled entirely.

### Actual behavior

Viewer/Contributor is able to make changes to the project name, description, instructions/pinned notes, and/or privacy, and when they click the Save button, the operation silently fails.

**Comment by ltseng** [comment] 2023-10-13 20:39
https://github.com/techmatters/terraso-mobile-client/assets/2730009/ba321fbc-abd6-426f-b946-b10cdc8db881

**Comment by paulschreiber** [comment] 2023-10-13 23:48
>Viewers and contributors should not be able to make changes to the project name, description, or privacy. The Save button should be hidden or disabled entirely.

Viewer/contributor should not 
- have an editable text field
- have a save button

**Comment by CourtneyLee333** [comment] 2024-04-23 19:29
@DerekCaelin I think in our permissions convos we decided to make the Project Settings tab hidden from Contributor and Viewer.

**Comment by tm-ruxandra** [comment] 2024-04-25 21:14
This was addressed by pull request [758](https://github.com/techmatters/terraso-mobile-client/pull/758). Issue is no longer reproducible because the settings screen is hidden for non-managers.

**Comment by DerekCaelin** [comment] 2024-04-30 18:26
Confirmed as resolved.

**Closed by DerekCaelin** 2024-04-30 18:26 UTC
Labels: bug, good first issue, slim MVP, permissions
