### ISSUE TITLE
App requires relaunch to sync updates to projects

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#662] opened 2023-12-04 22:16 UTC
### App Version

59

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I'm writing this issue generically to account for multiple types of updates that can be done. Currently, when I make a change to a project's name, description, or project notes/instructions on one device, a user on another device must relaunch the app to sync those changes. I would expect that at the very least, reloading the projects list or opening the project up again would sync those changes.

12/20/2023 update - this also applies to notes, i.e. if User 1 takes a note while User 2 is viewing the same site, User 2 will need to close and relaunch the app to view User 1's note.

### Steps to Reproduce

Have the app open on Device B as a project member while the following is done.

On Device A, as a project manager:
1. Open a project and modify the project title, description, or instructions/pinned note. 
2. Save the changes.

On Device B:
1. Open the projects tab (if the project title or description was modified)
2. Open the project itself (if the project title, description, or instructions/pinned note was modified)

### Expected behavior

The updated title, description, or instructions/pinned note are visible.

### Actual behavior

The previous title, description, or instructions/pinned note is visible.

**Comment by CourtneyLee333** [comment] 2024-05-22 18:17
@DerekCaelin This one also should be covered by the broader sync issue.

**Comment by DerekCaelin** [comment] 2024-05-22 19:06
Yes... I think this is a classic, "It's not a bug, it's just not yet an implemented feature" that will be addressed by completing:
- https://github.com/techmatters/terraso-product/issues/230

**Closed by DerekCaelin** 2024-05-22 19:06 UTC
Labels: bug, slim MVP
