### ISSUE TITLE
After leaving a project, the project remains visible to user

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#523] opened 2023-10-20 18:03 UTC
### App Version

48

### Platforms

- [X] iOS
- [x] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

User still can access project after leaving it

### Steps to Reproduce

1. Create a project
2. Invite another user and assign them as manager
3. leave the project
4. see issue

### Expected behavior

User should return to the project list, which should not contain the project just left. 

### Actual behavior

User continues to see the project, until they close the app and re-open their project list. 

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/30597125-fcac-451f-afbb-65014d4c4715

**Comment by ltseng** [comment] 2023-10-20 18:06
Project is also still visible in list of projects![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/30cdf531-63fb-4e9a-8507-1349c2826ee6)

**Comment by ltseng** [comment] 2023-10-20 21:46
Happens when I leave the project as a manager too

https://github.com/techmatters/terraso-mobile-client/assets/2730009/e34aab58-35b6-4d53-838d-54d85ce0eb68

**Comment by ltseng** [comment] 2023-10-25 18:58
The above also happens when I remove a contributor from the project. The contributor is still able to see the project in their projects list, as well as access all the sites that belong to the project.

**Comment by tm-ruxandra** [comment] 2024-04-25 21:20
Duplicate of https://github.com/techmatters/terraso-mobile-client/issues/550

**Comment by tm-ruxandra** [comment] 2024-04-25 21:21
Closed as duplicate.

**Closed by tm-ruxandra** 2024-04-25 21:21 UTC
Labels: bug, slim MVP, permissions, Engineering
