### ISSUE TITLE
Hide non-MVP inputs on site and project screens

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#808] opened 2024-01-25 19:00 UTC
We will only be focusing on Vertical Cracking, Slope Steepness/Shape, Soil Texture/Rock Fragments, and Soil Color for the first release of the app. This means that we need to hide mentions of the other input methods from the following places:

- project management inputs screen (section for required data inputs)
- site Soil tab ("three dot" menus for each soil depth interval)
- [Site Soil ID Info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3803%3A23430&mode=design&t=vOKXOdAKKHiKCYSS-1) (see Courtney's comment below)

**Comment by ltseng** [comment] 2024-01-25 19:00
@CourtneyLee333 can you think of any other places that we need to hide other data inputs?

**Comment by CourtneyLee333** [comment] 2024-01-25 19:31
The [Site Soil ID Info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3803%3A23430&mode=design&t=vOKXOdAKKHiKCYSS-1) shows the data comparison charts. Perhaps MVP should show pH and EC for the soil itself, but not show the charts where collected data will display.

**Comment by ltseng** [comment] 2024-01-25 19:48
Good idea

**Comment by DerekCaelin** [comment] 2024-06-06 14:07
Closing this issue as now a duplicate of: https://github.com/techmatters/terraso-mobile-client/issues/1382

> Site Soil ID Info sheet 
This is addressed in updated capri designs

**Closed by DerekCaelin** 2024-06-06 14:07 UTC
Labels: slim MVP
