### ISSUE TITLE
Styling changes for home screen map

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#405] opened 2023-09-05 15:46 UTC
- [ ] Selected location map marker should have the active style. This applies to tapping a non-site marker as well as site marker. [Here is the figma frame that shows the style.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=582%3A36087&mode=design&t=GyCe02aX8Wzncg6i-1)
- [ ] Site card popover on map should have drop shadow. [Here is the figma frame that shows the style.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=582%3A36087&mode=design&t=GyCe02aX8Wzncg6i-1)  
- [ ] Search bar should have an “x” button to clear the search term. 
- [ ] Tapping a map marker should center the marker and the popover
<img width="443" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/a643142b-7e42-4f82-a5a9-ffc40045d632">

**Comment by ltseng** [comment] 2023-09-19 19:46
@CourtneyLee333 and @Hanal-code after you have processed the usability study feedback, will you let me know which of these items you think should still be fixed? I'm looking specifically at the ones referring to zoom level, but any of these are fine to modify.

**Comment by CourtneyLee333** [comment] 2023-09-25 14:46
@Hanal-code I've put "ignore" on the list above for the bugs related to map zoom level. Otherwise I think the list is good. Do you agree?

**Comment by Hanal-code** [comment] 2023-09-25 15:39
@CourtneyLee333 Yes, the zoom level adjustment is not needed now.

**Comment by paulschreiber** [comment] 2023-10-11 20:24
Closing as duplicate of #436. Filed #492 for the popover offscreen.

**Closed by paulschreiber** 2023-10-11 20:24 UTC
Labels: bug, landpks
