### ISSUE TITLE
User who leaves project, or is removed from project, can still see project.

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#550] opened 2023-10-27 16:21 UTC
### App Version

48

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When a user leaves a project or is removed from the project by a Project Manager, I would expect that this user no longer can access the project. However, they still can.

### Steps to Reproduce

Leaving project

On Device A

1. As a non-Manager user, open a project and go to the Team tab
2. Click Leave Project

Being removed from a project

On Device A

1. As a Manager user, open a project that has another member beside yourself, and go to the Team tab
2. Tap the name of the user whom you want to remove.
3. Remove them from the project.

### Expected behavior

On Device B

The person who either left the project or was removed from the project should no longer be able to access the project or its sites from either the Projects list view or the Sites list view.

### Actual behavior

On Device B

The person who left or was removed can still access the project from their projects list, and can still see any of the sites attached to the project.

**Comment by paulschreiber** [comment] 2023-10-27 19:53
Are these actions occruing on two different device? This is not clear from the repro steps.

**Comment by ltseng** [comment] 2023-10-27 20:03
The repro steps all take place on one device, and the observed effects all take place on a different device

**Comment by paulschreiber** [comment] 2023-10-29 19:28
So this requires two devices to reproduce. That should be part of the streps (on device A, do 1, 2, 3; on device B, do 4 5 6). I suspect this is another case of the stale data/not syncing problem.

**Comment by ltseng** [comment] 2023-10-30 17:11
Probably is, though I want to point out that this persists between launches of the app

**Comment by ltseng** [comment] 2024-02-28 17:51
Still present in build 88 on iOS (and I assume build 87 on Android too)

**Comment by tm-ruxandra** [comment] 2024-04-25 19:40
Cannot reproduce -- need to coordinate w/ product to verify repro steps.

**Comment by tm-ruxandra** [comment] 2024-04-25 21:01
This issue will be covered by https://github.com/techmatters/terraso-product/issues/230, as it is a data synchronization issue.

**Comment by tm-ruxandra** [comment] 2024-04-25 21:02
Duplicate of https://github.com/techmatters/terraso-product/issues/230

**Closed** 2024-05-22 19:10 UTC
Labels: bug, slim MVP, permissions, Engineering
