### ISSUE TITLE
Remove "Last Modified" from Sites Card - Sites screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1342] opened 2024-05-16 19:24 UTC
Remove "Last Modified" field from cards in the sites list. To be re-introduced post-Capri: https://github.com/techmatters/terraso-product/issues/781

## Steps to see cards
1. Go to sites tab
2. pull up sites drawer
3. see cards

![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/1f4d4498-9bef-4458-9cd0-7ec54e44be06)

**Comment by paulschreiber** [comment] 2024-05-17 18:00
Duplicate of #1341. (There is only one card component.)

**Closed by paulschreiber** 2024-05-17 18:00 UTC
Labels: Engineering
