### ISSUE TITLE
Dev console warning: "Selector unknown returned a different result when called with the same parameters" on site screen

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1408] opened 2024-05-24 01:14 UTC
### App Version

dev build

### Platforms

- [ ] iOS
- [ ] Android
- [X] iOS simulator
- [X] Android emulator

### Description

As a dev, this is rather annoying, as I have to dismiss it every time to see all the site page content

### Steps to Reproduce

1. Go to a site

### Expected behavior

No warning appears

### Actual behavior

Warning appears: 
![Screenshot 2024-05-23 at 6 14 05 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/f47c4434-df0e-49e0-b2ca-d0da7dae9736) ![Screenshot 2024-05-23 at 6 13 37 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/edd9e6e3-91ea-4c82-a04f-328080f5ce4b)

**Comment by paulschreiber** [comment] 2024-07-02 20:38
Duplicate of #132..

**Closed** 2024-07-02 20:38 UTC
Labels: bug
