### ISSUE TITLE
Update Done/Submit buttons

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#714] opened 2023-12-20 17:52 UTC
When the keyboard is open, and there is a Done/Save/Submit FAB visible on screen:

- The Done/Save/Submit FAB should not rise above the keyboard
- All content should be made visible by scrolling

[Figma discussion for context](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1850-50032&mode=design&t=pVyGRRZhyGt1EWcT-0#645187560)

**Comment by DerekCaelin** [comment] 2024-07-15 15:47
This is now a duplicate of https://github.com/techmatters/terraso-mobile-client/issues/1314

**Closed by DerekCaelin** 2024-07-15 15:47 UTC
Labels: slim MVP
