### ISSUE TITLE
Build user settings screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#804] opened 2024-01-22 21:32 UTC
Provide a setting screen that enables a user to delete their account through an email request. 

[Figma design for User Settings screen](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5081%3A12379&mode=design&t=fkyv23y37AgoLCyl-1)

**Comment by CourtneyLee333** [comment] 2024-04-05 19:39
@DerekCaelin I added the link to the existing design, but this is going to change per our conversation about cutting out the side drawer nav for Capri MVP.

**Comment by DerekCaelin** [comment] 2024-04-22 19:44
Closing this issue as it is now a duplicate of : https://github.com/orgs/techmatters/projects/7/views/9?pane=issue&itemId=60613326

**Closed by DerekCaelin** 2024-04-22 19:44 UTC
Labels: slim MVP
