### ISSUE TITLE
Soil Info sheet - upon selecting "Create site", sheet remains open and user does not see form

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1556] opened 2024-06-13 19:35 UTC
### App Version

142

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The Soil Info sheet isn't closing when the user selects "create site" and the user doesn't see the form until they manually close the sheet

### Steps to Reproduce

1. tap map
2. select "learn more"
3. select "explore the data"
4. select a soil
5. scroll to the bottom of the sheet and tap "create site"

### Expected behavior

sheet closes and the user sees the "create site" form

### Actual behavior

sheet remains open, user needs to manually close it to see the form

**Comment by CourtneyLee333** [comment] 2024-06-27 19:47
I can repro this on v148.

**Comment by CourtneyLee333** [comment] 2024-07-05 16:54
@knipec I just reviewed this and think we should, instead, remove the Create Site Here button from the soil info sheet.

**Comment by knipec** [comment] 2024-07-05 19:57
Sweet, happy to just remove it :) 
That's the only place you know of that something navigates to another thing in an overlay sheet, right? 

For future engineer reference, this is because overlay sheets are not part of the navigation stack. I think it makes sense to as much as possible treat them as a dead end in navigation flow. However, if we do need to allow that in the future: 
- Approaches:
1. Pass a ref that allows the button to be able to close the overlay sheet when it is pressed (the simplest)
2. BottomSheetModalProvider used to be deeper in the component hierarchy than RootNavigator, but was pulled up outside of the RootNavigator to solve some other issue. It may be possible to introduce it further down the tree again, but this seems more complex because wouldn't want to break other things. 
(Also, there are 2 BottomSheetModalProviders at different levels of the component hierarchy: the outermost one is needed for ListFilters because paper components can open modals; don't recall what the innermost one is needed for.)
3. Some vague thought that overlay sheets in general could be closed when navigation happens, but that seems least simple.

**Comment by knipec** [comment] 2024-07-05 19:58
For future engineer reference, this is because overlay sheets are not part of the navigation stack. I think it makes sense to as much as possible treat them as a dead end in navigation flow. However, if we do need to allow that in the future: 
- Approaches:
1. Pass a ref that allows the button to be able to close the overlay sheet when it is pressed (the simplest)
2. BottomSheetModalProvider used to be deeper in the component hierarchy than RootNavigator, but was pulled up outside of the RootNavigator to solve some other issue. It may be possible to introduce it further down the tree again, but this seems more complex because wouldn't want to break other things. 
(Also, there are 2 BottomSheetModalProviders at different levels of the component hierarchy: the outermost one is needed for ListFilters because paper components can open modals; don't recall what the innermost one is needed for.)
3. Some vague thought that overlay sheets in general could be closed when navigation happens, but that seems least simple.

**Comment by CourtneyLee333** [comment] 2024-07-05 20:09
Currently we have a stack of overlay sheets in this path:
Top Soil Matches > open a soil info overlay sheet > tap on InfoButton for Location Score or Soil Properties Score > opens info overlay sheet

It seems to switch one overlay sheet for the other, but the Location Score and Soil Properties Score sheets are currently implemented incorrectly and need to be rebuilt with the proper component. If we need to make overlay sheets a dead end in this case, I think making the soil info sheet a screen instead would probably be best.

**Comment by knipec** [comment] 2024-07-05 20:15
Ok, I think that's fine! 
This is confusing because there are two different libraries at play: the `react-navigation` library, and the `gorhom` library for bottom sheets / overlay sheets. 
In the case you mention it's actually just opening another `gorhom` sheet, not using the `react-navigation` library (via our `useNavigation` hook) to navigate sheets. So there still wouldn't be "navigation" stuff coming from the overlay sheet.

**Comment by paulschreiber** [comment] 2024-07-08 22:30
Confirmed this is fixed in 159.

**Closed by paulschreiber** 2024-07-08 22:30 UTC
Labels: bug, Engineering
