### ISSUE TITLE
Show counter for project title character count

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#434] opened 2023-09-18 21:13 UTC
The ultimate implementation depends on the design pattern that engineers choose. At minimum, we need to tell users what the max number of possible characters for the project title are. Ideally, we would be able to show a dynamically updating counter for the number of used characters / max number of characters.

**Comment by DerekCaelin** [comment] 2024-06-12 17:37
Now duplicate of: https://github.com/techmatters/terraso-mobile-client/issues/1318

**Closed** 2024-08-02 18:53 UTC
Labels: slim MVP
