### ISSUE TITLE
Edit/Delete Notes option only shows when clicking the pencil icon

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#713] opened 2023-12-19 20:16 UTC
### App Version

66

### Platforms

- [x] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Currently tapping on the body of a note displays a read-only experience, even if the user is the note author. Tapping anywhere on the note card should launch the editing experience where the user can make and save changes to the note, or delete the note. 

### Steps to Reproduce

1. Open a site where you have created a note
2. Tap the body of the site note (not the pencil icon)
3. See issue

### Expected behavior

 Should launch the note editing experience for user who created the note. Edit icon should not appear otherwise.

### Actual behavior

Launches a "read-only" view of the note

**Comment by ltseng** [comment] 2023-12-20 21:36
I didn't realize this until attempting to test this on iOS and seeing a more obtrusive highlighting of the pencil icon background - this is probably on purpose. If I tap the general note card, I see the note, but not the delete option, or the ability to tap in and start making edits. If I tap the edit icon directly, then I see both. 

@CourtneyLee333 is this expected?

**Comment by CourtneyLee333** [comment] 2023-12-21 14:21
This is not the expected behavior. A regular should be editable on the first tap of the edit icon. This screen - [Manager Pinned Note sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2523%3A10334&mode=design&t=TC8gdspQ5FtREGI4-1) - is what the user should see when they've tapped the Pinned Note. The user should not have the option to edit it, only to open it and close it. It's my understanding that if a manager wants to edit that Pinned Note they need to do so from the Project Management section.

**Comment by CourtneyLee333** [comment] 2023-12-21 14:28
It looks to me that when I've created a note:

- I tap the edit icon to edit the note and see the Delete and Done buttons. 
- I tap elsewhere on the note card to read the note, and I see the Close button but not the editing features. 

This is confusing, and we should simplify:
- If I created the note, I should always have the editing features on my note no matter where I tap on the note card to open it. 

Also, the intention is that we don't truncate regular Site Notes the way we do the Pinned Note. So I don't need to be able to open someone else's Site Note because I can read all of it without opening it.

**Comment by ltseng** [comment] 2023-12-26 17:30
This makes sense. I will update this ticket to reflect your suggestion above.

**Comment by ltseng** [comment] 2023-12-26 17:42
@CourtneyLee333 will you read through the bug report above and let me know if what I have documented for next steps/expected behavior matches your vision?

**Comment by CourtneyLee333** [comment] 2023-12-26 17:48
@ltseng Looks good to me!

**Comment by ltseng** [comment] 2023-12-26 17:48
Thanks!

**Comment by ltseng** [comment] 2024-03-29 23:43
Also note that the Edit icon on a note appears to have shrunk drastically in recent updates. This screenshot is from build 105 on Android.

![Screenshot_20240329-174216_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/7c5dda7f-834c-429e-a4c2-d46ca6bffc32)

**Comment by DerekCaelin** [comment] 2024-06-12 17:03
Updated and simplified this issue.

**Closed** 2024-07-16 19:05 UTC
Labels: bug
