### ISSUE TITLE
Navigate user to project list when they leave a project

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#412] opened 2023-09-06 19:36 UTC
Currently a user will remain in a project view  if they leave the project. Instead they should be navigated to the project list.

For the [project users screen](https://www.figma.com/file/y3PqlW8Ih9NfFm0mFMl3IZ/LandPKS-Design-Prototype-CURRENT-10%2F6%2F23?type=design&node-id=221-19771&mode=dev), when clicking the red button "LEAVE PROJECT", the user should be navigated to the project list tab. The current behaviour is that the user remains in the project, but any actions they try and perform will fail, as they are no longer member of the project.

(We can ignore the confirmation modal for now, that will be implemented in another issue).

**Comment by ltseng** [comment] 2023-12-04 18:32
@david-code I feel like this is done already? Is this one still a valid task? Please close if not.

**Comment by ltseng** [comment] 2024-02-01 20:06
Closing as duplicate of #523

**Closed** 2024-02-01 22:43 UTC
Labels: landpks, slim MVP
