### ISSUE TITLE
Use Soil ID algorithm for temporary site popover 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1555] opened 2024-06-13 16:22 UTC
On temporary site site popover, use soil ID algorithm to generate `soil ID top match` and `ecological site top match`. (Currently we have hardcoded "Clifton")

## acceptance criteria
- [x] On temporary site popover, use Soil ID algorithm to fill
   - [x] Soil ID top match
   - [x] Ecological site top match

Should be available in v146

**Comment by CourtneyLee333** [comment] 2024-06-18 20:50
@tm-ruxandra I'm not sure what I'm supposed to see here. I do see loading indicators on the popover for Soil ID Top Match and Ecol. Site Top Match, but they say Yemassee and Loamy Rise... Is that expected at this point?

**Comment by tm-ruxandra** [comment] 2024-06-18 22:00
@CourtneyLee333 yes, because the soil ID algorithm is still returning pre-set data from the backend while @shrouxm works on fixing its crashes. It is expected that the data shown on the popover matches the data shown in the soil ID screens.

**Comment by paulschreiber** [comment] 2024-07-03 20:23
Confirmed this is fixed in 153.

**Closed by paulschreiber** 2024-07-03 20:23 UTC
Labels: Engineering
